name: Python Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Install dependencies (including flake8 or other linters, optional)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Run Python syntax check using 'python -m py_compile' (or flake8 for additional linting)
      - name: Check Python syntax errors
        run: |
          # Check all Python files for syntax errors
          for file in $(find . -name "*.py"); do
            python -m py_compile $file || exit 1
          done
